pygments: true
relative_permalinks: false
gauges_id: 503c5af6613f5d0f19000027
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: https://github.com/christopheducamp/docjekyll
#baseurl: http://christopheducamp.github.io/docjekyll
#url: http://localhost:4000