pygments: true
relative_permalinks: false
gauges_id: 503c5af6613f5d0f19000027
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: https://github.com/christopheducamp/docjekyll
<<<<<<< HEAD
baseurl: http://christopheducamp.github.io/docjekyll
=======
url: http://christopheducamp.github.io/docjekyll
>>>>>>> 312ec68ccf0d4acfa6c0e953c14203f05e692ef9
